[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino




upload_protocol = espota
upload_port = Put your ESP32's IP address here, I can help you find it




lib_deps =
    file://Path to ur lib here




monitor_speed = 115200
upload_flags =
    --auth=robot123
